import 'package:flutter/material.dart';

class RecruitInfoModel {
  const RecruitInfoModel({
    @required this.title,
    @required this.city,
    @required this.area,
    @required this.seniority,
    @required this.educationalLeve,
    @required this.salary,
    @required this.date,
    @required this.jobType,
    @required this.enterpriseAvatar,
    @required this.enterpriseName,
    @required this.enterpriseFinancing,
    @required this.enterpriseSize,
    @required this.enterpriseType,
  });
  final String title; // 标题
  final String city; // 市
  final String area; // 区
  final List<num> seniority; // 工龄
  final String educationalLeve; // 学历
  final List<num> salary; // avatar
  final String date;
  final List<num> jobType;
  final String enterpriseAvatar;
  final String enterpriseName;
  final String enterpriseFinancing; // 企业融资
  final List<num> enterpriseSize; // 企业规模员工数
  final List<String> enterpriseType;
}

class RecruitInfoModelsPageData {
  final List<RecruitInfoModel> list = [
    const RecruitInfoModel(
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/53.jpg',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/76.jpg',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/17.jpg',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/55.jpg',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/11.jpg',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
     enterpriseAvatar: 'https://randomuser.me/api/portraits/women/50.jpg',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/50.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/91.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/women/60.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/60.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/45.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/7.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/35.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/64.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar: 'https://randomuser.me/api/portraits/men/86.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar:
          'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537868900176&di=ddbe94a75a3cc33f880a5f3f675b8acd&imgtype=0&src=http%3A%2F%2Fs2.sinaimg.cn%2Fmw690%2F003wRTwMty6IGZWzd2p31',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
    const RecruitInfoModel(
      enterpriseAvatar:
          'https://timgsa.baidu.com/timg?image&quality=80&size=b10000_10000&sec=1537858866&di=fe35e4465c73122f14e1c9475dd68e47&src=http://a2.att.hudong.com/63/26/01300001128119143503262347361.jpg',
      title: '前端开发工程师',
      city: '杭州',
      area: '天目山',
      date: '03月22日',
      educationalLeve: '本科',
      enterpriseFinancing: 'B轮',
      enterpriseName: '小电影',
      enterpriseSize: <num>[150, 500],
      enterpriseType: <String>['移动互联网', '文化娱乐'],
      jobType: <num>[1, 2],
      salary: <num>[15, 25],
      seniority: <num>[3, 5],
    ),
  ];

  static RecruitInfoModelsPageData mock() {
    return RecruitInfoModelsPageData();
  }
}
